jobs:
  build:
    name: ${{ matrix.tasks.alias }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew assemble
    - continue-on-error: true
      name: Run task with Gradle
      run: ./gradlew ${{ matrix.tasks.name }}
    - continue-on-error: true
      if: (success() || failure()) && matrix.tasks.alias != 'benchmark'
      name: Archive task results
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.tasks.name }}-test-report
        path: '**/build/test-results/**/TEST-*.xml'
        retention-days: 90
    - continue-on-error: true
      if: success() || failure()
      name: Generate test summary
      uses: test-summary/action@v2
      with:
        paths: '**/build/test-results/**/TEST-*.xml'
        show: fail, skip
    strategy:
      fail-fast: false
      matrix:
        tasks:
        - alias: unitTests
          name: check
        - alias: integrationTests
          name: integrationTest
        - alias: slowIntegrationTests
          name: slowIntegrationTest
        - alias: benchmark
          name: jmh -Pjmh.iterations=1 -Pjmh.timeOnIteration=5s -Pjmh.warmupIterations=0
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
