jobs:
  validate-pr-labels:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Verify PR labels
      uses: jesusvasquez333/verify-pr-label-action@v1.4.0
      with:
        disable-reviews: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pull-request-number: ${{ github.event.pull_request.number }}
        valid-labels: bug, enhancement, ignore-for-release
name: PR label verification
on:
  repository_dispatch:
    types: trigger-ga___label-verification.yml
