jobs:
  check-links:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: .github/workflows/markdown-links-config.json
        folder-path: docs/docs
        use-quiet-mode: yes
        use-verbose-mode: yes
name: Markdown Links Check
on:
  repository_dispatch:
    types: trigger-ga___markdown-links-check.yml
