jobs:
  validation:
    name: Test report
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Grant execute permission for report downloader
      run: chmod +x ./.github/scripts/download_reports.sh
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Download past reports
      run: ./.github/scripts/download_reports.sh
    - continue-on-error: true
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - continue-on-error: true
      name: Aggregate reports
      run: python ./.github/scripts/reporter.py "test"
name: Test report
on:
  repository_dispatch:
    types: trigger-ga___test_report.yml
